baseURL = 'https://ialexandermoon.github.io'
languageCode = 'en-ca'
title = 'iAlexanderMoon'
author = "Ian Moon"

pygmentsCodefences = true
pygmentsStyle = "doom-one"

[params]
    logoText = "iAlexanderMoon"
    isBlogFocused = true
    showHeroImage = true
    showResumeButton = false
    math = true

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Following"
    pre = "home"
    url = "/following"
    weight = 15
  [[menu.main]]
    name = "Blog"
    pre = "pen-tool"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    name = "Docs"
    pre = "pen-tool"
    url = "/docs/"
    weight = 20
  [[menu.main]]
    name = "Search"
    weight = 40
    [[menu.main.params]]
      type = "search"
  [[menu.main]]
    name = "GitHub"
    weight = 50
    url = "https://github.com/iAlexanderMoon/iAlexanderMoon.github.io"
      [[menu.main.params]]
        icon = "github"



[module]
  [[module.imports]]
    path = 'github.com/imfing/hextra'

